version: '3.8'

services:
  zipkin:
    image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411" # Zipkin API
    networks:
      - telemetry-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - telemetry-network

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.91.0
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8889:8889" # Prometheus metrics exposed by collector
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      - zipkin
    networks:
      - telemetry-network

  service-a:
    build:
      context: ../../../../../Downloads/go-telemetry-main
      dockerfile: Dockerfile.service-a
    ports:
      - "8080:8080"
    environment:
      - SERVICE_B_URL=http://service-b:8081
    depends_on:
      - service-b
      - otel-collector
    networks:
      - telemetry-network

  service-b:
    build:
      context: ../../../../../Downloads/go-telemetry-main
      dockerfile: Dockerfile.service-b
    ports:
      - "8081:8081"
    environment:
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
    depends_on:
      - otel-collector
    networks:
      - telemetry-network

networks:
  telemetry-network:
    driver: bridge 